// ContactFormData is now exported from schema.ts (generated by Zod)
// Re-export for backwards compatibility
export type { ContactFormData } from './schema';

// Payload sent to Make.com webhook
export interface WebhookPayload {
  leadId: string;
  createdAt: string;
  source: string;
  contact: {
    fullName: string;
    email: string;
    phone: string;
  };
  product: string;
  message: string | null;
  meeting: {
    medium: string | null;
    datetime: string | null;
  };
  routing: {
    assignee: string;
  };
}

// API response
export interface SubmitResponse {
  success: boolean;
  message: string;
  error?: {
    type?: string;
    status?: number;
    statusText?: string;
    details?: string;
  };
}

// Toast notification
export interface ToastState {
  show: boolean;
  type: 'success' | 'error';
  message: string;
}

// Dropdown option
export interface SelectOption {
  value: string;
  label: string;
}
